site_name: Ka Mana Earthshots Webpage

nav:
  - Home: 'index.md'
  - Examples: 'examples.md'
  - Summer Intensive Workshop: 'summerworkshop.md'
  - About Us: 'about.md'

theme:
    name: material
    logo: img/Logo1.jpeg
    favicon: img/favicon.ico
